# Generated by Django 3.0 on 2021-05-12 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('option11', models.FloatField(default=0)),
                ('option12', models.FloatField(default=0)),
                ('option13', models.FloatField(default=0)),
                ('option21', models.FloatField(default=0)),
                ('option22', models.FloatField(default=0)),
                ('option23', models.FloatField(default=0)),
                ('option31', models.FloatField(default=0)),
                ('option32', models.FloatField(default=0)),
                ('option33', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
